# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'AnalogOfDisk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnalogOfDisk
	pod 'SnapKit', '~> 5.0.0'
    	pod 'Alamofire', '= 5.6.4'
	pod 'SDWebImage', '~> 5.0'

end
